source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'BrickRequest_Tests', :exclusive => true do
  pod 'BrickRequest', :path => '../'
  pod 'SwiftyJSON'
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
